name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4.0.0
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - run: govulncheck ./...
      shell: bash
